const products = [
    { name: "Toner", image: "images/IMG_5627.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5628.JPG", category: "toner" },
    { name: "Serum/Essence", image: "images/IMG_5629.JPG", category: "serum" },
    { name: "Toner", image: "images/IMG_5630.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5631.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5632.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5633.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5634.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5635.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5636.JPG", category: "toner" },
    { name: "Cleanser", image: "images/IMG_5637.JPG", category: "cleanser" },
    { name: "Cleanser", image: "images/IMG_5639.JPG", category: "cleanser" },
    { name: "Cleanser", image: "images/IMG_5640.JPG", category: "cleanser" },
    { name: "Toner", image: "images/IMG_5641.JPG", category: "toner" },
    { name: "Cleanser", image: "images/IMG_5642.JPG", category: "cleanser" },
    { name: "Serum/Essence", image: "images/IMG_5643.JPG", category: "serum" },
    { name: "Cleanser", image: "images/IMG_5644.JPG", category: "cleanser" },
    { name: "Serum/Essence", image: "images/IMG_5645.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5646.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5647.JPG", category: "serum" },
    { name: "Misc", image: "images/IMG_5648.JPG", category: "misc" },
    { name: "Hair", image: "images/IMG_5649.JPG", category: "hair" },
    { name: "Cleanser", image: "images/IMG_5650.JPG", category: "cleanser" },
    { name: "Serum/Essence", image: "images/IMG_5651.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5652.JPG", category: "serum" },
    { name: "Toner", image: "images/IMG_5653.JPG", category: "toner" },
    { name: "Cleanser", image: "images/IMG_5654.JPG", category: "cleanser" },
    { name: "Serum", image: "images/IMG_5655.JPG", category: "serum" },
    { name: "Makeup", image: "images/IMG_5656.JPG", category: "makeup" },
    { name: "Makeup", image: "images/IMG_5657.JPG", category: "makeup" },
    { name: "Cleanser", image: "images/IMG_5658.JPG", category: "cleanser" },
    { name: "Cream", image: "images/IMG_5659.JPG", category: "cream" },
    { name: "Cleanser", image: "images/IMG_5660.JPG", category: "cleanser" },
    { name: "Serum/Essence", image: "images/IMG_5661.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5662.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5663.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5664.JPG", category: "serum" },
    { name: "Makeup", image: "images/IMG_5666.JPG", category: "makeup" },
    { name: "Serum/Essence", image: "images/IMG_5667.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5668.JPG", category: "serum" },
    { name: "Makeup", image: "images/IMG_5669.JPG", category: "makeup" },
    { name: "Hair", image: "images/IMG_5670.JPG", category: "hair" },
    { name: "Hair", image: "images/IMG_5671.JPG", category: "hair" },
    { name: "Serum/Essence", image: "images/IMG_5672.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5673.JPG", category: "serum" },
    { name: "Cream", image: "images/IMG_5674.JPG", category: "cream" },
    { name: "Toner", image: "images/IMG_5675.JPG", category: "toner" },
    { name: "Serum/Essence", image: "images/IMG_5676.JPG", category: "serum" },
    { name: "Makeup", image: "images/IMG_5677.JPG", category: "makeup" }, // lip balm
    { name: "Cream", image: "images/IMG_5678.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5679.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5680.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5681.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5682.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5683.JPG", category: "cream" },
    { name: "Serum/Essence", image: "images/IMG_5684.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5685.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5686.JPG", category: "serum" },
    { name: "Makeup", image: "images/IMG_5687.JPG", category: "makeup" }, 
    { name: "Makeup", image: "images/IMG_5688.JPG", category: "makeup" }, // lip balm
    { name: "Makeup", image: "images/IMG_5689.JPG", category: "makeup" },
    { name: "Makeup", image: "images/IMG_5690.JPG", category: "makeup" },
    { name: "Makeup", image: "images/IMG_5691.JPG", category: "makeup" },
    { name: "Sunscreen", image: "images/IMG_5692.JPG", category: "sunscreen" },
    { name: "Toner", image: "images/IMG_5694.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5695.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5696.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5697.JPG", category: "toner" },
    { name: "Cleanser", image: "images/IMG_5698.JPG", category: "cleanser" },
    { name: "Cleanser", image: "images/IMG_5699.JPG", category: "cleanser" },
    { name: "Cleanser", image: "images/IMG_5700.JPG", category: "cleanser" },
    { name: "Face Mask", image: "images/IMG_5701.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5702.JPG", category: "facemask" },
    { name: "Cream", image: "images/IMG_5703.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5704.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5705.JPG", category: "cream" },
    { name: "Serum/Essence", image: "images/IMG_5706.JPG", category: "serum" },
    { name: "Misc", image: "images/IMG_5707.JPG", category: "misc" },
    { name: "Misc", image: "images/IMG_5708.JPG", category: "misc" },
    { name: "Misc", image: "images/IMG_5709.JPG", category: "misc" }, // facial spray
    { name: "Misc", image: "images/IMG_5710.JPG", category: "misc" }, // facial spray
    { name: "Makeup", image: "images/IMG_5712.JPG", category: "makeup" },
    { name: "Serum/Essence", image: "images/IMG_5713.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5714.JPG", category: "serum" },
    { name: "Cream", image: "images/IMG_5715.JPG", category: "cream" },
    { name: "Serum/Essence", image: "images/IMG_5716.JPG", category: "serum" },
    { name: "Sunscreen", image: "images/IMG_5717.JPG", category: "sunscreen" },
    { name: "Cleanser", image: "images/IMG_5718.JPG", category: "cleanser" },
    { name: "Cream", image: "images/IMG_5719.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5720.JPG", category: "cream" },
    { name: "Serum/Essence", image: "images/IMG_5721.JPG", category: "serum" },
    { name: "Misc", image: "images/IMG_5722.JPG", category: "misc" },
    { name: "Misc", image: "images/IMG_5723.JPG", category: "misc" },
    { name: "Serum/Essence", image: "images/IMG_5724.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5725.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5726.JPG", category: "serum" },
    { name: "Toner", image: "images/IMG_5727.JPG", category: "toner" },
    { name: "Cleanser", image: "images/IMG_5728.JPG", category: "cleanser" },
    { name: "Face Mask", image: "images/IMG_5729.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5730.JPG", category: "facemask" },
    { name: "Cream", image: "images/IMG_5731.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5732.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5733.JPG", category: "cream" },
    { name: "Face Mask", image: "images/IMG_5734.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5735.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5736.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5738.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5740.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5741.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5742.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5743.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5745.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5746.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5747.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5748.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5750.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5751.JPG", category: "facemask" },
    { name: "Face Mask", image: "images/IMG_5753.JPG", category: "facemask" },
    { name: "Toner", image: "images/IMG_5754.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5755.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5756.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5757.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5758.JPG", category: "toner" },
    { name: "Cleanser", image: "images/IMG_5759.JPG", category: "cleanser" },
    { name: "Serum/Essence", image: "images/IMG_5760.JPG", category: "serum" },
    { name: "Misc", image: "images/IMG_5761.JPG", category: "misc" },
    { name: "Misc", image: "images/IMG_5762.JPG", category: "misc" },
    { name: "Misc", image: "images/IMG_5763.JPG", category: "misc" },
    { name: "Misc", image: "images/IMG_5764.JPG", category: "misc" },
    { name: "Cleanser", image: "images/IMG_5767.JPG", category: "cleanser" },
    { name: "Cleanser", image: "images/IMG_5768.JPG", category: "cleanser" },
    { name: "Cleanser", image: "images/IMG_5769.JPG", category: "cleanser" },
    { name: "Toner", image: "images/IMG_5771.JPG", category: "toner" },
    { name: "Serum/Essence", image: "images/IMG_5772.JPG", category: "serum" },
    { name: "Serum/Essence", image: "images/IMG_5773.JPG", category: "serum" },
    { name: "Cleanser", image: "images/IMG_5774.JPG", category: "cleanser" },
    { name: "Cream", image: "images/IMG_5775.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5776.JPG", category: "cream" },
    { name: "Makeup", image: "images/IMG_5777.JPG", category: "makeup" },
    { name: "Makeup", image: "images/IMG_5778.JPG", category: "makeup" },
    { name: "Face Mask", image: "images/IMG_5780.JPG", category: "facemask" },
    { name: "Misc", image: "images/IMG_5781.JPG", category: "misc" },
    { name: "Misc", image: "images/IMG_5782.JPG", category: "misc" },
    { name: "Hair", image: "images/IMG_5683.JPG", category: "hair" },
    { name: "Toner", image: "images/IMG_5785.JPG", category: "toner" },
    { name: "Toner", image: "images/IMG_5786.JPG", category: "toner" },
    { name: "Sunscreen", image: "images/IMG_5787.JPG", category: "sunscreen" },
    { name: "Sunscreen", image: "images/IMG_5788.JPG", category: "sunscreen" },
    { name: "Sunscreen", image: "images/IMG_5789.JPG", category: "sunscreen" },
    { name: "Cream", image: "images/IMG_5790.JPG", category: "cream" },
    { name: "Cream", image: "images/IMG_5791.JPG", category: "cream" },
    { name: "Misc", image: "images/IMG_5792.JPG", category: "misc" },
    { name: "Face Mask", image: "images/IMG_5793.JPG", category: "facemask" },
];

